# System utilities
SYSTEM_UTILS=(
	htop
	btop
	1password
	lazygit
	stow
	nerdfetch
	fzf
	zip
	unzip
	wget
	curl
	s-tui
	systemctl-tui
	duf
)

# Development tools
DEV_TOOLS=(
	vim
	yazi
	bat
	zsh
	neovim
	starship
	tmux
	ghostty
	git
	asdf-vm
	kitty
	librewolf
)

# System maintenance
MAINTENANCE=(
)

# Desktop environment
DESKTOP=(
	ly
)

# Media packages
MEDIA=(
	vlc
	gimp
	element-desktop
)

# Fonts
FONTS=(
	noto-fonts
	noto-fonts-emoji
)

# Services to enable
SERVICES=(
	NetworkManager.service
)
